name: Gerar Instalador IPK para TV (Pasta Tools)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    # Usamos o 22.04 porque ele aceita melhor ferramentas externas
    runs-on: ubuntu-22.04

    steps:
      - name: Baixando o Código do Paulo
        uses: actions/checkout@v4

      - name: Preparando o Computador do GitHub
        run: |
          sudo apt-get update
          # Instalamos os motores de base (Qt5) individualmente
          sudo apt-get install -y qtbase5-dev qt5-qmake qtbase5-dev-tools qtdeclarative5-dev qtwebengine5-dev build-essential

      - name: Configurando a Pasta Tools do Paulo
        run: |
          # Cria a pasta caso você ainda não tenha criado no GitHub
          mkdir -p tools
          # Dá permissão para o robô ler tudo que estiver lá dentro
          chmod -R +x tools/
          # Avisa o sistema para procurar programas dentro da sua pasta 'tools'
          echo "$(pwd)/tools" >> $GITHUB_PATH

      - name: Instalando Ferramentas da LG (WebOS CLI)
        run: |
          # Tentativa de instalação forçada do comando 'ares-package'
          sudo npm install -g @webos-tools/cli --unsafe-perm

      - name: Compilando o Motor C++ (Nativo)
        run: |
          qmake -qt=qt5
          make

      - name: Criando o Pacote .IPK Final
        run: |
          mkdir -p build
          # O robô tenta usar o ares-package (do sistema ou da sua pasta tools)
          ares-package . --out ./build

      - name: Salvar o Arquivo para o Paulo Baixar
        uses: actions/upload-artifact@v4
        with:
          name: Instalador-Google-TV
          path: ./build/*.ipk
