name: Gerar Instalador IPK para TV

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    # Esta linha é a mais importante: força o sistema Ubuntu 22.04
    runs-on: ubuntu-22.04

    steps:
      - name: Baixando o Código do Paulo
        uses: actions/checkout@v4

      - name: Preparando o Computador do GitHub
        run: |
          sudo apt-get update
          # Instalamos os pacotes um por um sem usar o 'qt5-default'
          sudo apt-get install -y qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools qtdeclarative5-dev qtwebengine5-dev build-essential

      - name: Instalando Ferramentas da LG (WebOS CLI)
        run: |
          sudo npm install -g @webos-tools/cli

      - name: Compilando o Motor C++ (Nativo)
        run: |
          # Comando para usar o motor Qt5 no Ubuntu 22.04
          qmake -qt=qt5
          make

      - name: Criando o Pacote .IPK Final
        run: |
          mkdir -p build
          ares-package . --out ./build

      - name: Salvar o Arquivo para o Paulo Baixar
        uses: actions/upload-artifact@v4
        with:
          name: Instalador-Google-TV
          path: ./build/*.ipk
