name: Build IPK Paulo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Baixando o Codigo
        uses: actions/checkout@v4

      - name: Instalar Ferramentas LG
        run: |
          sudo npm install -g @webos-tools/cli --unsafe-perm

      - name: Gerar Pacote IPK
        run: |
          # Cria a pasta de saída
          mkdir -p build
          # O comando ares-package empacota os arquivos HTML/JS/JSON que estão na raiz
          ares-package . --out ./build

      - name: Download do Arquivo Final
        uses: actions/upload-artifact@v4
        with:
          name: App-Paulo-TV
          path: ./build/*.ipk
