name: Build IPK Paulo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Baixando o Codigo
        uses: actions/checkout@v4

      - name: Instalar Ferramentas LG
        run: |
          sudo npm install -g @webos-tools/cli --unsafe-perm

      - name: Gerar Pacote IPK
        run: |
          mkdir -p build
          # Baixa uma imagem provisoria de icone para o robo parar de dar erro 255!
          wget -qO icon.png https://github.com/fluidicon.png
          
          # Agora ele gera o pacote sem reclamar
          ares-package . --out ./build

      - name: Download do Arquivo Final
        uses: actions/upload-artifact@v4
        with:
          name: App-Paulo-TV
          path: ./build/*.ipk
